apiVersion: skaffold/v4beta13
kind: Config

build:

  tagPolicy:
    sha256: {}
    
  artifacts:

    - image: ai-orchestration
      context: ai-orchestration
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "src/**"

    - image: auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "src/**"

    - image: agent
      context: sandbox/agent
      docker:
        dockerfile: dockerfile

    - image: router
      context: sandbox/router
      docker:
        dockerfile: dockerfile

    - image: sandbox
      context: sandbox/server
      docker:
        dockerfile: dockerfile

    - image: template
      context: sandbox/template
      docker:
        dockerfile: dockerfile

manifests:
  rawYaml:
    - K8s/ai-deployment.yml
    - K8s/ai-service.yml
    - K8s/auth-deployment.yml
    - K8s/auth-service.yml
    - K8s/sandbox-deployment.yml
    - K8s/sandbox-service.yml
    - K8s/ingress.yml
    - K8s/router-deployment.yml
    - K8s/router-service.yml
    - K8s/rbac.yml
    - K8s/secrets.yml

