import { HumanMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue,ReducedValue, StateGraph, START, END, type GraphNode } from "@langchain/langgraph";
import { mistralModel,cohereModel,geminiModel } from "./model.service.js";
import { createAgent,providerStrategy,toolStrategy } from "langchain";
import {z} from "zod";

// --- Shared types ---

export type JudgeResult = {
    solution_1_score: number;
    solution_2_score: number;
    solution_1_reasoning: string;
    solution_2_reasoning: string;
};

export type SolutionResult = {
    solution_1: string;
    solution_2: string;
};

// --- Core logic functions (callable from both graph nodes AND socket service) ---

export async function runSolutions(problem: string): Promise<SolutionResult> {
    const [mistral_solution, cohere_solution] = await Promise.all([
        mistralModel.invoke(problem),
        cohereModel.invoke(problem)
    ]);
    return {
        solution_1: mistral_solution.text ?? "",
        solution_2: cohere_solution.text ?? "",
    };
}

export async function runJudge(
    problem: string,
    solution_1: string,
    solution_2: string
): Promise<JudgeResult> {
    const judge = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10),
            solution_2_score: z.number().min(0).max(10),
            solution_1_reasoning: z.string(),
            solution_2_reasoning: z.string(),
        })),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    });

    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    });

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = judgeResponse.structuredResponse;

    return {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning,
    };
}

// --- LangGraph state & nodes (use core functions internally) ---

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const solutionNode: GraphNode<typeof state> = async (state)=>{
    const result = await runSolutions(state.problem);
    return {
        solution_1: result.solution_1,
        solution_2: result.solution_2,
    };
}

const judgeNode: GraphNode<typeof state> = async (state)=>{
    const {problem, solution_1, solution_2} = state;
    const judgeResult = await runJudge(problem, solution_1, solution_2);
    return {
        judge: judgeResult,
    };
}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

   export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}
